adds log levels and log messages
SSeastCoders/user-service pull request #25
Opened 2021-10-12 03:00 UTC by arolonss

2021-10-12 21:49 UTC, hazelbakerharvey commented
Did you add an error level logging?

2021-10-12 22:03 UTC, hazelbakerharvey requested changes
I left a bunch of comments! Generally I think this could use more error logging esp with custom constraints etc. I also think we dont need trace, debug and info all together. I would remove the trace and debug mostly, but if you want that info switch them to info logs. I like that you have made the amount of logs diff depending on the environment!!

2021-10-12 22:03 UTC, hazelbakerharvey commented on users-api/src/main/java/com/ss/eastcoderbank/usersapi/service/AuthService.java
> +        LOGGER.debug(s);
Just commenting on this example, i think debug should be used for only debugging purposes. not necessarily in any develop version

2021-10-12 22:03 UTC, hazelbakerharvey commented on users-api/src/main/java/com/ss/eastcoderbank/usersapi/security/JwtAuthenticationFilter.java
> +            LOGGER.error(e.getMessage());
Nvm about my previous question about error level! i was just looking at the properties. Why use get message here and other places a custom message?

2021-10-12 22:03 UTC, hazelbakerharvey commented on users-api/src/main/java/com/ss/eastcoderbank/usersapi/security/JwtAuthorizationFilter.java
> +        LOGGER.trace("JwtAuthorizationFilter.doFilterInternal reached...");
I think trace is also used for debugging, but for more detail. https://www.papertrail.com/solution/tips/logging-in-java-best-practices-and-tips/

2021-10-12 22:03 UTC, hazelbakerharvey commented on users-api/src/main/java/com/ss/eastcoderbank/usersapi/service/UserService.java
> +        LOGGER.trace("UserService.getUsersByRole reached...");
Like this trace and debug i think would be better as info

2021-10-12 22:03 UTC, hazelbakerharvey commented on users-api/src/main/java/com/ss/eastcoderbank/usersapi/service/UserService.java
> +        LOGGER.info("Creating user profile...");
Same here. this pattern of trace, debug and info should probably be all info. I think also we might not need this level of detail like logging the dto itself

2021-10-12 22:03 UTC, hazelbakerharvey commented on users-api/src/main/java/com/ss/eastcoderbank/usersapi/service/UserService.java
> +            LOGGER.info(e.getMessage(), e);
probably should be error

2021-10-12 22:03 UTC, hazelbakerharvey commented on users-api/src/main/java/com/ss/eastcoderbank/usersapi/service/UserService.java
>                  handleUniqueConstraints(((ConstraintViolationException) thr).getConstraintName());
needs an error log?

2021-10-12 22:03 UTC, hazelbakerharvey commented on users-api/src/main/java/com/ss/eastcoderbank/usersapi/service/UserService.java
>              req = userRepository.findAll(PageRequest.of(pageNumber, pageSize, Sort.by(asc ? Sort.Direction.ASC : Sort.Direction.DESC, sort))).map(user -> userMapper.mapToDto(user));
could be even more verbose, ie "Sorting enabled"

2021-10-12 22:03 UTC, hazelbakerharvey commented on users-api/src/main/java/com/ss/eastcoderbank/usersapi/service/UserService.java
>      protected void handleUniqueConstraints(String constraint) {
this needs a bunch more error logs?

2021-10-12 22:04 UTC, asernass commented on users-api/src/main/java/com/ss/eastcoderbank/usersapi/controller/UserController.java
> +        LOGGER.info("Getting inactive users...");
I wouldn't put trace and debug logs in the controller handling the request. I would move those to the services that call them.

2021-10-12 22:07 UTC, arolonss commented on users-api/src/main/java/com/ss/eastcoderbank/usersapi/security/JwtAuthenticationFilter.java
> +            LOGGER.error(e.getMessage());
I left was not sure if it was serving a purpose to anyone else at the time but I am happy to change it to a custom message if needed.

2021-10-14 13:53 UTC, arolonss commented
> I left a bunch of comments! Generally I think this could use more error logging esp with custom constraints etc. I also think we dont need trace, debug and info all together. I would remove the trace and debug mostly, but if you want that info switch them to info logs. I like that you have made the amount of logs diff depending on the environment!!

Great! Thanks for the review, I will get to makes those changes today.

2021-10-14 13:54 UTC, arolonss commented on users-api/src/main/java/com/ss/eastcoderbank/usersapi/controller/UserController.java
> +        LOGGER.info("Getting inactive users...");
> I wouldn't put trace and debug logs in the controller handling the request. I would move those to the services that call them.

Thanks, I will get to that today.

2021-10-18 19:07 UTC, merged